name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9daa107b4459f918629e73b91bde2837d2cc433be040141f6b5603707e0d0a7e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
