name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "573c627f4bccf9b166f289a1756891a6affd408d46c69ccb494d8d44272841da"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
