name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce70fea26370cf814111a06a734328e4c6706f5f6ff3f05a04327a8a49f8e2cc"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
