name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47c387e50fe3675ba0f81d4bf5c53fbf74894bf21eda96ed80980e1104d3b1ea"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
