name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93fddc5b3abec44bdf4186afcbfbf7bf6be7698f8df3142e2e51a7c0548ff9bb"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
