name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cc842db68de9964b67a85eb376920ac00e5bb27e7c27f176e7070c8c7068532"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
