name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ef516b95994fcff449b5b6b45a91e815e02c780ec29a43e794692922863f775"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
