name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c6f90f92be4b10cf20174b9221c9ade0e391b38882badb7966bc5a6ba50672"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
