name = "WeenieCraft 1.21.4"
author = "Morgan H."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ca936083b4f3b11fa5f4c3e328683237bcf86155b0a1fb4b33d83fdfce8b5ed"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
